### ISSUE TITLE
Add notifier implementation of adapter

### ISSUE THREAD

**Issue by mrstegeman** [rzr/mastodon-lite#7]
Now that the WebThings Gateway has support for notifiers (coming in 0.9), it would be great to implement that interface.

[Notifiers](https://github.com/mozilla-iot/gateway/issues/1758) essentially act as a rule output. That way, we don't have to add Things that are not actually devices, when their only purpose is to notify the user (or some other channel).

For examples, see:
* mozilla-iot/email-sender-adapter#3 and mozilla-iot/email-sender-adapter#5
* mozilla-iot/lg-tv-adapter#9

**Comment by rzr** [comment]
Excellent, by the way I wrote also a "mastodon sensor" too that update content from a feed, but it's an html string, would this be used to display popup notification on dashboard ? or eventually I could redirect to an external thingy for display.

**Comment by mrstegeman** [comment]
We do support toast notifications, but they're only really intended for specific use cases, such as showing why an add-on failed to load or for showing a pairing/unpairing prompt.

**Comment by rzr** [comment]
yes it makes sense, and external addons could be in charge of it...

**Comment by rzr** [comment]
To be released in:

https://github.com/mozilla-iot/addon-list/pull/661

**Comment by mrstegeman** [comment]
I don't see a notifier in the code.

**Comment by rzr** [comment]
It's now Released
